sgl-project/genai-bench

USER_GUIDE.md, examples/plot_configs/README.md, examples/plot_configs/comprehensive_multi_line.json, examples/plot_configs/custom_2x2.json, examples/plot_configs/multi_line_latency.json, examples/plot_configs/performance_focused.json, genai_bench/analysis/flexible_plot_report.py, genai_bench/analysis/plot_config.py, genai_bench/analysis/plot_report.py, genai_bench/cli/report.py
Refactor plotting system to support custom plot configurations beyond the fixed 2x4 layout. Users can now define any grid layout and select any fields from AggregatedMetrics for plotting.
- Flexible Plot Configuration (plot_config.py)
- JSON-based configuration system for custom plot layouts
- Support for any NxM grid layout (1x1 to 5x6)
- Field path mapping from AggregatedMetrics (direct fields + stats.*.{measure})
- Two built-in presets: "2x4_default" (original layout), "simple_2x2"
- Dynamic Plot Generation (flexible_plot_report.py)
- FlexiblePlotGenerator class for configuration-driven plotting
- Support for line, scatter, and bar plot types
- Custom titles, labels, and positioning
- Graceful error handling with fallback to original system
- Automatic hiding of unused subplot …
=> feat: Support flexible plot configuration

genai_bench/sampling/text.py, genai_bench/utils.py, tests/sampling/test_base.py
Fix left tokens to sample in _sample_text
Motivation:
The line is divided if the number of tokens on it is greater than needed. Specifically, from the sample_text function:
if tokens > left_tokens_to_sample:
prompt += line[:left_tokens_to_sample]
This part essentially assumes that each token is a character, even though this isn't true. 
Changes:
Abstract a function to calculate the char_token_ratio and then multiply it by the left tokens to sample to get prompt from line.
=> [BUG] Fix left tokens to sample in _sample_text

docs/.config/mkdocs-gh-pages.yml
This PR fixes the issue where the deployed documentation at https://docs.sglang.ai/genai-bench/ was not using the Material theme despite it working
locally.
- The `mkdocs-gh-pages.yml` was using the `INHERIT` directive to inherit from a non-existent config file
- The relative path inheritance wasn't working correctly when the config file is in a subdirectory
- The `docs_dir` and `site_dir` paths were incorrect for the GitHub Actions workflow context
- Replaced the `INHERIT` directive with the full Material theme configuration
- Fixed the `docs_dir` path from `../` to `docs` (relative to repository root)
- Fixed the `site_dir` path from `../../site` to `site` (relative to repository root)
- Updated the `site_url` to the correct domain: `https://docs.sglang.ai/genai-bench`
The documentation …
=> [bugfix] mkdocs gh pages config inheritance issue

genai_bench/cli/option_groups.py
Fix typo in the help message of `--traffic-scenario`.
`Supported scenarios for  are:` => `Supported scenarios are:`
=> fix(cli): fix typo in the help message of `--traffic-scenario`

docs/.config/mkdocs-gh-pages.yml
This pull request removes a non-existent entry of plot examples `examples/plot-config-examples.md` in mkdocs.
=> docs: remove non-existent entry of plot examples in mkdocs

genai_bench/auth/oci/model_auth_adapter.py, tests/auth/oci/test_model_auth_adapter.py
OCIModelAuthAdapter.get_credentials() should return signer instead of auth object. It's causing the GenerativeAiInferenceClient initialization failure.
1. Fixed get_credentials() method
2. Fixed unit test
=> [Bug Fix] OCIModelAuthAdapter.get_credentials() returning wrong object type

genai_bench/sampling/text.py, tests/sampling/test_text.py
This PR addresses two issues in the TextSampler class:
1. Token-based truncation (fixes #30)
Previously, the _sample_text method was truncating lines by character count `(line[:left_tokens_to_sample])`, which could led to significant discrepancies when lines contained many tokens. This was particularly problematic for datasets with long lines or non-standard tokenization patterns.
Fix: Now we properly encode each line to tokens and truncate at the exact token boundary:
- Use `tokenizer.encode(line)` to get the actual token representation
- Truncate the token list to the exact number needed
- Decode only the truncated tokens back to text
This ensures the returned prompt contains exactly the requested number of tokens, not an approximation based on character positions.
2. Unique document …
=> [Bugfix] Fix token-based truncation and document duplication in TextSampler

Makefile, genai_bench/cli/option_groups.py, genai_bench/cli/validation.py, genai_bench/data/config.py, genai_bench/data/loaders/base.py, genai_bench/data/loaders/factory.py, genai_bench/data/loaders/image.py, genai_bench/sampling/image.py, genai_bench/user/aws_bedrock_user.py, genai_bench/user/azure_openai_user.py, genai_bench/user/cohere_user.py, genai_bench/user/gcp_vertex_user.py, genai_bench/user/oci_cohere_user.py, genai_bench/user/oci_genai_user.py, genai_bench/user/openai_user.py, tests/data/loaders/test_factory.py, tests/data/loaders/test_image.py, tests/data/test_config.py, tests/sampling/test_image.py, tests/user/test_aws_bedrock_user.py, tests/user/test_azure_openai_user.py, tests/user/test_gcp_vertex_user.py, tests/user/test_oci_cohere_user.py, tests/user/test_oci_genai_user.py, tests/user/test_openai_user.py
The current `ImageSampler` has the following issues:
1. Limited Prompt Extraction
It simply relies on `prompt_column` to extract prompt. However, most of the HuggingFace multimodal datasets don't have a string type of prompt available for straightforward extraction. For instance, [lmms-lab/LLaVA-OneVision-Data](https://huggingface.co/datasets/lmms-lab/LLaVA-OneVision-Data) stores prompts within nested conversation structures:
```
{
"conversations": [
{"from": "human", "value": "What is shown in this image?"},
{"from": "gpt", "value": "The image shows..."}
]
}
```
This requires complex extraction logic that cannot be handled by a simple column reference.
2. Forced Image Resizing with Scenarios
- It tries to resize the image despite dataset characteristics. For specific datasets, users …
=> feat: Add flexible image dataset support and make scenarios optional

genai_bench/data/config.py, genai_bench/data/loaders/base.py
- When testing image benchmark with very large images, the pillow library throws an exception.
```
│ /home/vasheno/genai-bench/.venv/lib/python3.12/site-packages/PIL/Image.py:3449 in _decompression_bomb_check                     │               
│                                                                                                                                 │               
│   3446 │   │   │   f"Image size ({pixels} pixels) exceeds limit of {2 * MAX_IMAGE_PIXELS} "                                     │               
│   3447 │   │   │   "pixels, could be decompression bomb DOS attack."                                                            │               
│   3448 │   │   ) …
```
=> [Bugfix] Allow for benchmarking using large images.

genai_bench/sampling/text.py, tests/sampling/test_text.py
`tokenizer.encode(line)` in `_sample_text` did not specify `add_special_tokens=False` but `self.get_token_length` sets `add_special_tokens=False`. This causes great discrepancy. Hence, `_check_discrepancy` will alway log warning.
- Sets `tokenizer.encode(line, add_special_tokens=False)`
=> bugfix: Fix TextSampler sampling logic

docs/user-guide/run-benchmark.md, genai_bench/cli/cli.py, genai_bench/cli/option_groups.py, genai_bench/distributed/runner.py, pyproject.toml, tests/cli/test_cli_benchmark.py, tests/distributed/test_runner.py
Add spawn-rate option to prevent worker overload in distributed benchmarks
- Add `--spawn-rate` CLI option to control user spawning rate (defaults to concurrency)
- Improve worker process error handling and cleanup
Resolves: Worker processes being killed and restarted due to
inability to respond to heartbeats when spawning 500+ users immediately.
When running high-concurrency benchmarks with large payloads (e.g., 20k+ tokens), workers may become overwhelmed if all users are spawned immediately. This can cause worker heartbeat failures and restarts.
To prevent this, we can use the --spawn-rate option to control how quickly users are spawned:
```
--num-concurrency 500 \
--num-workers 16 \
--spawn-rate 50
```
Examples:
--spawn-rate 50: Spawn 50 users per second (takes 10 seconds to reach 500 …
=> Add spawn rate to prevent worker overload in distributed benchmarks

genai_bench/cli/__init__.py, genai_bench/cli/utils.py, genai_bench/cli/validation.py, genai_bench/sampling/image.py, tests/sampling/test_image.py
- genai-bench is currently relying on scenario to control the whole benchmark logic.
- Allowing traffic-scenario to be None brings the overall complexity in the flow.
- Revert the changes in ImageSampler to allow None traffic scenario for now until we have a better design.
- HF dataset logging is useful at the beginning of the benchmark, bring it back.
- Revert the changes that allow `traffic scenario` to be `None` for `ImageSampler`.
- Add back `DEFAULT_SCENARIOS_FOR_VISION`
- Remove `set_environment_variables()`
=> bugfix: Bring back HF dataset logging and scenario for images

genai_bench/user/aws_bedrock_user.py, genai_bench/user/azure_openai_user.py, genai_bench/user/gcp_vertex_user.py, tests/user/test_aws_bedrock_user.py, tests/user/test_azure_openai_user.py, tests/user/test_gcp_vertex_user.py
Motivation:
Several of the user classes (AzureOpenAI, GCPVertex, AWSBedrock) had `image-to-text` as a supported task instead of `image-text-to-text`. 
Changes:
Replaced `image-to-text` with `image-text-to-text` in the relevant user classes and tests.
=> [Bugfix] Use image-text-to-text instead of image-to-text

genai_bench/analysis/excel_report.py, tests/analysis/test_excel_na.py
When benchmarking scenarios fail to meet the minimum output inference speed requirement (10 tokens/s for text tasks, 100 tokens/s for embedding tasks), the Excel summary report displayed a confusing sentinel value (-9999) instead of a user-friendly indication. This made it difficult for users to understand when their benchmarks didn't meet performance expectations.
- logged warning and display N/A when the speed requirement is not met
- Added unit test
=> [Misc] Improve Excel report handling when performance threshold is not met

docs/development/contributing.md, docs/development/index.md, docs/getting-started/installation.md, docs/getting-started/task-definition.md, docs/user-guide/multi-cloud-auth-storage.md, docs/user-guide/multi-cloud-quick-reference.md, docs/user-guide/run-benchmark-using-docker.md, docs/user-guide/run-benchmark.md, docs/user-guide/upload-benchmark-result.md, genai_bench/data/loaders/text.py
Fixed some outdated/incorrect information in the documentation.
Changes:
- Update version on installation page
- Swap old 'image-to-text' for 'image-text-to-text' in various places
- Bump v0.0.1 to v0.0.2 for the docker container instructions
- Fixed markdown in various places
=> [Docs] Fix errors in docs

genai_bench/cli/cli.py, genai_bench/data/config.py, genai_bench/data/loaders/image.py, genai_bench/logging.py, genai_bench/sampling/base.py, genai_bench/sampling/image.py, genai_bench/sampling/text.py, genai_bench/utils.py, tests/data/loaders/test_image.py, tests/sampling/test_image.py
When trying to execute the benchmark below, the `ImageDatasetLoader` processes for a long time.
The dataset config is:
```
{
"source": {
"type": "huggingface",
"path": "zhang0jhon/Aesthetic-4K",
"huggingface_kwargs": {
"split": "train"
}
},
"prompt_column": "text",
"image_column": "image",
"unsafe_allow_large_images": true
}
```
And without commit 7895404, it appears as the benchmark is stuck. This is because with a large dataset like `zhang0jhon/Aesthetic-4K`, (which has around 1.5k rows), the for loop in `ImageSampler._process_loaded_data` needs to take a O(n) time.
This PR tries to resolve this by moving the image and prompt extraction logic into `ImageSampler`.
- Image loader: stop eager iteration; return `datasets.Dataset` as-is; for
`DatasetDict` auto-select a split (prefer 'train', …
=> feat(data): normalize HF dataset types and enable lazy image sampling

genai_bench/analysis/flexible_plot_report.py, genai_bench/analysis/plot_report.py, genai_bench/cli/cli.py, tests/analysis/test_plot_report.py
Currently, `plot_graph` uses matplotlib's autoscaling to decide the axis value range plus a margin. This sometimes makes the x-axis or y-axis start from a negative number. This PR tries to set the general scale starting from 0.
- Re-enable autoscaling after each series, then re-apply only the bound we care about.
- X: autoscale, then set left=0 while keeping the autoscaled right.
- Y: autoscale, then set bottom=0 only if y-scale is linear; skip on log.
- Make all annotation backgrounds transparent by setting bbox alpha to 0.
- In stacked error-rate plots, autoscale y then pin bottom=0 so multiple groups can extend the top bound.
=> Remove hidden cap for data and set general scale start from 0

genai_bench/sampling/text.py
The `tolerance` param in `_check_discrepancy` is too strict. In sgl-router's CI, the warning keeps popping up. The warnings are not very insightful here because 144 is less than 5% of 8000 tokens. `tolerance` is hard to control as it should be differentiated by the number of prefill tokens.
- Remove `tolerance` in `_check_discrepancy`
=> [Misc] Remove tolerance in `_check_discrepancy`

docs/user-guide/generate-plot.md, docs/user-guide/run-benchmark.md, examples/plot_configs/custom_2x2.json, genai_bench/analysis/excel_report.py, genai_bench/analysis/flexible_plot_report.py, genai_bench/analysis/plot_config.py, genai_bench/analysis/plot_report.py, genai_bench/cli/cli.py, genai_bench/cli/option_groups.py, genai_bench/cli/report.py, genai_bench/metrics/aggregated_metrics_collector.py, genai_bench/protocol.py, genai_bench/time_units.py, genai_bench/ui/dashboard.py, genai_bench/ui/layout.py, genai_bench/ui/plots.py, tests/analysis/test_excel_na.py, tests/analysis/test_plot_config.py, tests/analysis/test_plot_report.py, tests/cli/test_report.py, tests/test_time_units.py, tests/ui/test_dashboard.py
Some users would prefer using milliseconds for latency measures (TTFT, E2E Latency, etc.) rather than seconds. See also: https://github.com/sgl-project/genai-bench/issues/4
- Added `--time-unit [s|ms]` to select the desired unit for latency measures to `genai-bench benchmark`, `genai-bench excel` and `genai-bench plot`
- Updated docs and added tests
For benchmarking:
- The specified time unit (seconds by default) is written into the experiment metadata
- The generated excel sheet, and intermediate plots on the dashboard will have their values and labels modified accordingly (e.g., the old TTFT label will now read TTFT (s) or TTFT (ms)).
For excel:
- Time unit is specified for latency measures in the column headers
- Values are converted from the source time unit (derived from experiment …
=> [Report] Add option for milliseconds

.github/pull_request_template.md, docs/development/contributing.md
This PR introduces a standardized pull request template for **genai-bench**.  
The template consolidates PR requirements previously documented in the contributing guide, ensuring contributors consistently follow the same process when opening a PR.
Closes #78
- Added `.github/pull_request_template.md` including:
- PR type classification ([Bugfix], [Core], [Docs], etc.)
- Commit message conventions (title ≤ 52 chars, lines ≤ 72 chars)
- Checklist for rebasing, linting, testing, and documentation updates
- Updated `docs/development/contributing.md`:
- Removed duplicate PR requirements section
- Added a short reference to the PR template
=> [Docs] Add PR template and remove duplicate PR section from contributing guide

.github/workflows/release.yml
- Ship an official Docker image to **GHCR** as part of each release, alongside the **PyPI** package.  
- Ensure a **single source of truth** for versioning by updating `pyproject.toml` in a PR before creating the release.  
- Provide **multi-arch images** (`linux/amd64`, `linux/arm64`) for broader runtime support.  
- Use the **moirai-internal namespace** in GHCR, which has specific write permissions to ensure controlled publishing.  
We now **manually update `pyproject.toml`** in a PR, merge it, and then create the **tag/release** from that commit.  
This ensures the tag, release metadata, and `pyproject.toml` version always match.  
**Pros**
- **Single source of truth** — `pyproject.toml` always reflects the real current version.  
- **Consistency** — release tag, package metadata, and …
=> [CI] add GHCR publish to release

genai_bench/ui/dashboard.py, tests/ui/test_dashboard.py
Bugfix: Fix the following crash with minimal dashboard:
```TypeError: MinimalDashboard.update_scatter_plot_panel() takes 2 positional arguments but 3 were given```
/kind Bug
- Added a test to make sure the crashing minimaldashboard function doesn't crash
- To reproduce original error (and verify fix works) prepend `ENABLE_UI=false` to the genai-bench benchmark command. This invokes the MinimalDashboard, which previously would crash but now does not.
=> [UI] Fix Minimal Dashboard
